apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-sofs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: flexvolume-smb-k8s-sofs
  flexVolume:
    driver: "microsoft.com/smb"
  secretRef:
  name: smbcreds
  options:
    source: "//k8s-sofs.lab.nerbelir.com/k8s-pv-elk"
    mountoptions: "vers=3.0,dir_mode=0777,file_mode=0777"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: flexvolume-smb-k8s-sofs
provisioner: k8s-sofs.lab.nerbelir.com/k8s-pv-elk
mountOptions:

vers=3.0
dir_mode=0777
file_mode=0777
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
name: quickstart
spec:
version: 7.5.2
nodeSets:

name: default
count: 1
config:
node.master: true
node.data: true
node.ingest: true
node.store.allow_mmap: false
volumeClaimTemplates:
metadata:
name: elasticsearch-data
spec:
accessModes:
ReadWriteOnce
resources:
requests:
storage: 5Gi
storageClassName: flexvolume-smb-k8s-sofs