# Define parameters
namespace: elastic-system

name: elasticsearch

version: 7.6.2

appVersion: 7.6.2

esJavaOpts: "-Xms1g -Xmx1g"

ElclusterName: "elk"

tag: Dev

kibana:
  replicaCount: 1


master:
  replicaCount: 1
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "local-path"
    resources:
      requests:
        storage: 100M
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"

data:
  replicaCount: 2
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "local-path"
    resources:
      requests:
        storage: 100M
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"