# Arun: File is modified to furnish few exceptional configurations
# 1- Using generated cerficate
# 2- Scheduling using node selector
# kubectl label nodes <node> <label-key>=<label-value>
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: "{{ .Values.ElclusterName }}-{{ .Values.tag | lower }}-om"
  namespace: {{ .Values.namespace }}
spec:
  version: 7.6.2
  nodeSets:
  - name: master
    count: {{ .Values.master.replicaCount }}
    config:
      node.master: true
      node.data: false
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          chart: "{{ .Chart.Name }}"
      spec:
        nodeSelector:
          xnum: node-1
          environment: production
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "{{ .Values.esJavaOpts }}"
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: default
  - name: data
    count: {{ .Values.data.replicaCount }}
    config:
      node.master: false
      node.data: true
      node.ingest: true
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        nodeSelector:
          xnum: node-2
          environment: production
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: default
